#include "../include/cartridge.h"
#include <commons/log.h>
#include <stdio.h>

log_t cartdrige_logger = {.file = "log.log",
                          .process = "CARTRIDGE",
                          .level = LOG_LEVEL_DEBUG,
                          .is_active_console = 1};

t_log_level log_level = LOG_LEVEL_DEBUG;

cartdrige_header *get_cartdrige_header() {
  return (cartdrige_header *)ram_read(0x100);
}

void cartdrige_load(const char *filename) {
  cartdrige_logger.logger =
      log_create(cartdrige_logger.file, cartdrige_logger.process,
                 cartdrige_logger.is_active_console, cartdrige_logger.level);
  FILE *file = safe_fopen(cartdrige_logger.logger, filename, "r");
  rewind(file);

  fseek(file, 0, SEEK_END);

  u32 size = ftell(file);
  u8 *stream = safe_malloc(NULL, size);

  rewind(file);
  fread(stream, sizeof(u8), size, file);

  ram_write(stream, size, 0x0);
  free(stream);

  fclose(file);
}

static const char *ROM_TYPES[] = {
    "ROM ONLY",
    "MBC1",
    "MBC1+RAM",
    "MBC1+RAM+BATTERY",
    "0x04 ???",
    "MBC2",
    "MBC2+BATTERY",
    "0x07 ???",
    "ROM+RAM 1",
    "ROM+RAM+BATTERY 1",
    "0x0A ???",
    "MMM01",
    "MMM01+RAM",
    "MMM01+RAM+BATTERY",
    "0x0E ???",
    "MBC3+TIMER+BATTERY",
    "MBC3+TIMER+RAM+BATTERY 2",
    "MBC3",
    "MBC3+RAM 2",
    "MBC3+RAM+BATTERY 2",
    "0x14 ???",
    "0x15 ???",
    "0x16 ???",
    "0x17 ???",
    "0x18 ???",
    "MBC5",
    "MBC5+RAM",
    "MBC5+RAM+BATTERY",
    "MBC5+RUMBLE",
    "MBC5+RUMBLE+RAM",
    "MBC5+RUMBLE+RAM+BATTERY",
    "0x1F ???",
    "MBC6",
    "0x21 ???",
    "MBC7+SENSOR+RUMBLE+RAM+BATTERY",
};

static const char *OLD_LIC_CODES[0x100] = {
    [0x00] = "None",
    [0x01] = "Nintendo",
    [0x08] = "Capcom",
    [0x09] = "HOT-B",
    [0x0A] = "Jaleco",
    [0x0B] = "Coconuts Japan",
    [0x0C] = "Elite Systems",
    [0x13] = "EA (Electronic Arts)",
    [0x18] = "Hudson Soft",
    [0x19] = "ITC Entertainment",
    [0x1A] = "Yanoman",
    [0x1D] = "Japan Clary",
    [0x1F] = "Virgin Games Ltd.3",
    [0x24] = "PCM Complete",
    [0x25] = "San-X",
    [0x28] = "Kemco",
    [0x29] = "SETA Corporation",
    [0x30] = "Infogrames5",
    [0x31] = "Nintendo",
    [0x32] = "Bandai",
    [0x34] = "Konami",
    [0x35] = "HectorSoft",
    [0x38] = "Capcom",
    [0x39] = "Banpresto",
    [0x3C] = "Entertainment Interactive (stub)",
    [0x3E] = "Gremlin",
    [0x41] = "Ubi Soft1",
    [0x42] = "Atlus",
    [0x44] = "Malibu Interactive",
    [0x46] = "Angel",
    [0x47] = "Spectrum HoloByte",
    [0x49] = "Irem",
    [0x4A] = "Virgin Games Ltd.3",
    [0x4D] = "Malibu Interactive",
    [0x4F] = "U.S. Gold",
    [0x50] = "Absolute",
    [0x51] = "Acclaim Entertainment",
    [0x52] = "Activision",
    [0x53] = "Sammy USA Corporation",
    [0x54] = "GameTek",
    [0x55] = "Park Place13",
    [0x56] = "LJN",
    [0x57] = "Matchbox",
    [0x59] = "Milton Bradley Company",
    [0x5A] = "Mindscape",
    [0x5B] = "Romstar",
    [0x5C] = "Naxat Soft14",
    [0x5D] = "Tradewest",
    [0x60] = "Titus Interactive",
    [0x61] = "Virgin Games Ltd.3",
    [0x67] = "Ocean Software",
    [0x69] = "EA (Electronic Arts)",
    [0x6E] = "Elite Systems",
    [0x6F] = "Electro Brain",
    [0x70] = "Infogrames5",
    [0x71] = "Interplay Entertainment",
    [0x72] = "Broderbund",
    [0x73] = "Sculptured Software6",
    [0x75] = "The Sales Curve Limited7",
    [0x78] = "THQ",
    [0x79] = "Accolade15",
    [0x7A] = "Triffix Entertainment",
    [0x7C] = "MicroProse",
    [0x7F] = "Kemco",
    [0x80] = "Misawa Entertainment",
    [0x83] = "LOZC G.",
    [0x86] = "Tokuma Shoten",
    [0x8B] = "Bullet-Proof Software2",
    [0x8C] = "Vic Tokai Corp.16",
    [0x8E] = "Ape Inc.17",
    [0x8F] = "I’Max18",
    [0x91] = "Chunsoft Co.8",
    [0x92] = "Video System",
    [0x93] = "Tsubaraya Productions",
    [0x95] = "Varie",
    [0x96] = "Yonezawa19/S’Pal",
    [0x97] = "Kemco",
    [0x99] = "Arc",
    [0x9A] = "Nihon Bussan",
    [0x9B] = "Tecmo",
    [0x9C] = "Imagineer",
    [0x9D] = "Banpresto",
    [0x9F] = "Nova",
    [0xA1] = "Hori Electric",
    [0xA2] = "Bandai",
    [0xA4] = "Konami",
    [0xA6] = "Kawada",
    [0xA7] = "Takara",
    [0xA9] = "Technos Japan",
    [0xAA] = "Broderbund",
    [0xAC] = "Toei Animation",
    [0xAD] = "Toho",
    [0xAF] = "Namco",
    [0xB0] = "Acclaim Entertainment",
    [0xB1] = "ASCII Corporation or Nexsoft",
    [0xB2] = "Bandai",
    [0xB4] = "Square Enix",
    [0xB6] = "HAL Laboratory",
    [0xB7] = "SNK",
    [0xB9] = "Pony Canyon",
    [0xBA] = "Culture Brain",
    [0xBB] = "Sunsoft",
    [0xBD] = "Sony Imagesoft",
    [0xBF] = "Sammy Corporation",
    [0xC0] = "Taito",
    [0xC2] = "Kemco",
    [0xC3] = "Square",
    [0xC4] = "Tokuma Shoten",
    [0xC5] = "Data East",
    [0xC6] = "Tonkin House",
    [0xC8] = "Koei",
    [0xC9] = "UFL",
    [0xCA] = "Ultra Games",
    [0xCB] = "VAP, Inc.",
    [0xCC] = "Use Corporation",
    [0xCD] = "Meldac",
    [0xCE] = "Pony Canyon",
    [0xCF] = "Angel",
    [0xD0] = "Taito",
    [0xD1] = "SOFEL (Software Engineering Lab)",
    [0xD2] = "Quest",
    [0xD3] = "Sigma Enterprises",
    [0xD4] = "ASK Kodansha Co.",
    [0xD6] = "Naxat Soft14",
    [0xD7] = "Copya System",
    [0xD9] = "Banpresto",
    [0xDA] = "Tomy",
    [0xDB] = "LJN",
    [0xDD] = "Nippon Computer Systems",
    [0xDE] = "Human Ent.",
    [0xDF] = "Altron",
    [0xE0] = "Jaleco",
    [0xE1] = "Towa Chiki",
    [0xE2] = "Yutaka # Needs more info",
    [0xE3] = "Varie",
    [0xE5] = "Epoch",
    [0xE7] = "Athena",
    [0xE8] = "Asmik Ace Entertainment",
    [0xE9] = "Natsume",
    [0xEA] = "King Records",
    [0xEB] = "Atlus",
    [0xEC] = "Epic/Sony Records",
    [0xEE] = "IGS",
    [0xF0] = "A Wave",
    [0xF3] = "Extreme Entertainment",
    [0xFF] = "LJN"};

static const char *NEW_LIC_CODES[0xFFFF] = {
    [0x3030] = "None",
    [0x3031] = "Nintendo Research & Development 1",
    [0x3038] = "Capcom",
    [0x3133] = "EA (Electronic Arts)",
    [0x3138] = "Hudson Soft",
    [0x3139] = "B-AI",
    [0x3230] = "KSS",
    [0x3232] = "Planning Office WADA",
    [0x3234] = "PCM Complete",
    [0x3235] = "San-X",
    [0x3238] = "Kemco",
    [0x3239] = "SETA Corporation",
    [0x3330] = "Viacom",
    [0x3331] = "Nintendo",
    [0x3332] = "Bandai",
    [0x3333] = "Ocean Software/Acclaim Entertainment",
    [0x3334] = "Konami",
    [0x3335] = "HectorSoft",
    [0x3337] = "Taito",
    [0x3338] = "Hudson Soft",
    [0x3339] = "Banpresto",
    [0x3431] = "Ubi Soft1",
    [0x3432] = "Atlus",
    [0x3434] = "Malibu Interactive",
    [0x3436] = "Angel",
    [0x3437] = "Bullet-Proof Software2",
    [0x3439] = "Irem",
    [0x3530] = "Absolute",
    [0x3531] = "Acclaim Entertainment",
    [0x3532] = "Activision",
    [0x3533] = "Sammy USA Corporation",
    [0x3534] = "Konami",
    [0x3535] = "Hi Tech Expressions",
    [0x3536] = "LJN",
    [0x3537] = "Matchbox",
    [0x3538] = "Mattel",
    [0x3539] = "Milton Bradley Company",
    [0x3630] = "Titus Interactive",
    [0x3631] = "Virgin Games Ltd.3",
    [0x3634] = "Lucasfilm Games4",
    [0x3637] = "Ocean Software",
    [0x3639] = "EA (Electronic Arts)",
    [0x3730] = "Infogrames5",
    [0x3731] = "Interplay Entertainment",
    [0x3732] = "Broderbund",
    [0x3733] = "Sculptured Software6",
    [0x3735] = "The Sales Curve Limited7",
    [0x3738] = "THQ",
    [0x3739] = "Accolade",
    [0x3830] = "Misawa Entertainment",
    [0x3833] = "lozc",
    [0x3836] = "Tokuma Shoten",
    [0x3837] = "Tsukuda Original",
    [0x3931] = "Chunsoft Co.8",
    [0x3932] = "Video System",
    [0x3933] = "Ocean Software/Acclaim Entertainment",
    [0x3935] = "Varie",
    [0x3936] = "Yonezawa/s’pal",
    [0x3937] = "Kaneko",
    [0x3939] = "Pack-In-Video",
    [0x3948] = "Bottom Up",
    [0x4134] = "Konami (Yu-Gi-Oh!)",
    [0x424C] = "MTO",
    [0x444B] = "Kodansha",
};

const char *get_rom_type(u8 code) { return ROM_TYPES[code]; }

const char *get_licensee(u8 old_code, u8 new_code) {
  if (old_code == 0x33) {
    const char *name = NEW_LIC_CODES[new_code];
    if (name == NULL)
      return "UNKNOWN";
    return name;
  }

    const char *name = OLD_LIC_CODES[old_code];
    if (name == NULL)
      return "UNKNOWN";
    return name;
}
