#include "../include/instructions.h"

#define NONE                                                                   \
  (operand) { OT_NONE, R_NONE }
#define REG(r)                                                                 \
  (operand) { OT_REG, r }
#define REG16(r)                                                               \
  (operand) { OT_REG16, r }
#define IMM8                                                                   \
  (operand) { OT_IMM8, R_NONE }
#define IMM16                                                                  \
  (operand) { OT_IMM16, R_NONE }
#define MEM_REG(r)                                                             \
  (operand) { OT_MEM_REG, r }
#define MEM_IMM16                                                              \
  (operand) { OT_MEM_IMM16, R_NONE }
#define MEM_IMM8                                                               \
  (operand) { OT_MEM_IMM8, R_NONE }
#define MEM_C                                                                  \
  (operand) { OT_MEM_C, R_C }
#define MEM_REG_INC(r)                                                         \
  (operand) { OT_MEM_REG_INC, r }
#define MEM_REG_DEC(r)                                                         \
  (operand) { OT_MEM_REG_DEC, r }

instruction instruction_table[] = {
    [0x00] = {NOP, NONE, NONE},
    [0x01] = {LD, REG16(R_BC), IMM16},
    [0x02] = {LD, MEM_REG(R_BC), REG(R_A)},
    [0x03] = {INC, REG16(R_BC), NONE},
    [0x04] = {INC, REG(R_B), NONE},
    [0x05] = {DEC, REG(R_B), NONE},
    [0x06] = {LD, REG(R_B), IMM8},
    [0x07] = {RLCA, NONE, NONE},
    [0x08] = {LD, MEM_IMM16, REG16(R_SP)},
    [0x09] = {ADD, REG16(R_HL), REG16(R_BC)},
    [0x0A] = {LD, REG(R_A), MEM_REG(R_BC)},
    [0x0B] = {DEC, REG16(R_BC), NONE},
    [0x0C] = {INC, REG(R_C), NONE},
    [0x0D] = {DEC, REG(R_C), NONE},
    [0x0E] = {LD, REG(R_C), IMM8},
    [0x0F] = {RRCA, NONE, NONE},

    [0x10] = {STOP, IMM8, NONE},
    [0x11] = {LD, REG16(R_DE), IMM16},
    [0x12] = {LD, MEM_REG(R_DE), REG(R_A)},
    [0x13] = {INC, REG16(R_DE), NONE},
    [0x14] = {INC, REG(R_D), NONE},
    [0x15] = {DEC, REG(R_D), NONE},
    [0x16] = {LD, REG(R_D), IMM8},
    [0x17] = {RLA, NONE, NONE},
    [0x18] = {JR, IMM8, NONE},
    [0x19] = {ADD, REG16(R_HL), REG16(R_DE)},
    [0x1A] = {LD, REG(R_A), MEM_REG(R_DE)},
    [0x1B] = {DEC, REG16(R_DE), NONE},
    [0x1C] = {INC, REG(R_E), NONE},
    [0x1D] = {DEC, REG(R_E), NONE},
    [0x1E] = {LD, REG(R_E), IMM8},
    [0x1F] = {RRA, NONE, NONE},

    [0x20] = {JR_NZ, IMM8, NONE},
    [0x21] = {LD, REG16(R_HL), IMM16},
    [0x22] = {LD, MEM_REG_INC(R_HL), REG(R_A)},
    [0x23] = {INC, REG16(R_HL), NONE},
    [0x24] = {INC, REG(R_H), NONE},
    [0x25] = {DEC, REG(R_H), NONE},
    [0x26] = {LD, REG(R_H), IMM8},
    [0x27] = {DAA, NONE, NONE},
    [0x28] = {JR_Z, IMM8, NONE},
    [0x29] = {ADD, REG16(R_HL), REG16(R_HL)},
    [0x2A] = {LD, REG(R_A), MEM_REG_INC(R_HL)},
    [0x2B] = {DEC, REG16(R_HL), NONE},
    [0x2C] = {INC, REG(R_L), NONE},
    [0x2D] = {DEC, REG(R_L), NONE},
    [0x2E] = {LD, REG(R_L), IMM8},
    [0x2F] = {CPL, NONE, NONE},

    [0x30] = {JR_NC, IMM8, NONE},
    [0x31] = {LD, REG16(R_SP), IMM16},
    [0x32] = {LD, MEM_REG_DEC(R_HL), REG(R_A)},
    [0x33] = {INC, REG16(R_SP), NONE},
    [0x34] = {INC, MEM_REG(R_HL), NONE},
    [0x35] = {DEC, MEM_REG(R_HL), NONE},
    [0x36] = {LD, MEM_REG(R_HL), IMM8},
    [0x37] = {SCF, NONE, NONE},
    [0x38] = {JR_C, IMM8, NONE},
    [0x39] = {ADD, REG16(R_HL), REG16(R_SP)},
    [0x3A] = {LD, REG(R_A), MEM_REG_DEC(R_HL)},
    [0x3B] = {DEC, REG16(R_SP), NONE},
    [0x3C] = {INC, REG(R_A), NONE},
    [0x3D] = {DEC, REG(R_A), NONE},
    [0x3E] = {LD, REG(R_A), IMM8},
    [0x3F] = {CCF, NONE, NONE},

    [0x40] = {LD, REG(R_B), REG(R_B)},
    [0x41] = {LD, REG(R_B), REG(R_C)},
    [0x42] = {LD, REG(R_B), REG(R_D)},
    [0x43] = {LD, REG(R_B), REG(R_E)},
    [0x44] = {LD, REG(R_B), REG(R_H)},
    [0x45] = {LD, REG(R_B), REG(R_L)},
    [0x46] = {LD, REG(R_B), MEM_REG(R_HL)},
    [0x47] = {LD, REG(R_B), REG(R_A)},
    [0x48] = {LD, REG(R_C), REG(R_B)},
    [0x49] = {LD, REG(R_C), REG(R_C)},
    [0x4A] = {LD, REG(R_C), REG(R_D)},
    [0x4B] = {LD, REG(R_C), REG(R_E)},
    [0x4C] = {LD, REG(R_C), REG(R_H)},
    [0x4D] = {LD, REG(R_C), REG(R_L)},
    [0x4E] = {LD, REG(R_C), MEM_REG(R_HL)},
    [0x4F] = {LD, REG(R_C), REG(R_A)},

    [0x50] = {LD, REG(R_D), REG(R_B)},
    [0x51] = {LD, REG(R_D), REG(R_C)},
    [0x52] = {LD, REG(R_D), REG(R_D)},
    [0x53] = {LD, REG(R_D), REG(R_E)},
    [0x54] = {LD, REG(R_D), REG(R_H)},
    [0x55] = {LD, REG(R_D), REG(R_L)},
    [0x56] = {LD, REG(R_D), MEM_REG(R_HL)},
    [0x57] = {LD, REG(R_D), REG(R_A)},
    [0x58] = {LD, REG(R_E), REG(R_B)},
    [0x59] = {LD, REG(R_E), REG(R_C)},
    [0x5A] = {LD, REG(R_E), REG(R_D)},
    [0x5B] = {LD, REG(R_E), REG(R_E)},
    [0x5C] = {LD, REG(R_E), REG(R_H)},
    [0x5D] = {LD, REG(R_E), REG(R_L)},
    [0x5E] = {LD, REG(R_E), MEM_REG(R_HL)},
    [0x5F] = {LD, REG(R_E), REG(R_A)},

    [0x60] = {LD, REG(R_H), REG(R_B)},
    [0x61] = {LD, REG(R_H), REG(R_C)},
    [0x62] = {LD, REG(R_H), REG(R_D)},
    [0x63] = {LD, REG(R_H), REG(R_E)},
    [0x64] = {LD, REG(R_H), REG(R_H)},
    [0x65] = {LD, REG(R_H), REG(R_L)},
    [0x66] = {LD, REG(R_H), MEM_REG(R_HL)},
    [0x67] = {LD, REG(R_H), REG(R_A)},
    [0x68] = {LD, REG(R_L), REG(R_B)},
    [0x69] = {LD, REG(R_L), REG(R_C)},
    [0x6A] = {LD, REG(R_L), REG(R_D)},
    [0x6B] = {LD, REG(R_L), REG(R_E)},
    [0x6C] = {LD, REG(R_L), REG(R_H)},
    [0x6D] = {LD, REG(R_L), REG(R_L)},
    [0x6E] = {LD, REG(R_L), MEM_REG(R_HL)},
    [0x6F] = {LD, REG(R_L), REG(R_A)},

    [0x70] = {LD, MEM_REG(R_HL), REG(R_B)},
    [0x71] = {LD, MEM_REG(R_HL), REG(R_C)},
    [0x72] = {LD, MEM_REG(R_HL), REG(R_D)},
    [0x73] = {LD, MEM_REG(R_HL), REG(R_E)},
    [0x74] = {LD, MEM_REG(R_HL), REG(R_H)},
    [0x75] = {LD, MEM_REG(R_HL), REG(R_L)},
    [0x76] = {HALT, NONE, NONE},
    [0x77] = {LD, MEM_REG(R_HL), REG(R_A)},
    [0x78] = {LD, REG(R_A), REG(R_B)},
    [0x79] = {LD, REG(R_A), REG(R_C)},
    [0x7A] = {LD, REG(R_A), REG(R_D)},
    [0x7B] = {LD, REG(R_A), REG(R_E)},
    [0x7C] = {LD, REG(R_A), REG(R_H)},
    [0x7D] = {LD, REG(R_A), REG(R_L)},
    [0x7E] = {LD, REG(R_A), MEM_REG(R_HL)},
    [0x7F] = {LD, REG(R_A), REG(R_A)},

    [0x80] = {ADD, REG(R_A), REG(R_B)},
    [0x81] = {ADD, REG(R_A), REG(R_C)},
    [0x82] = {ADD, REG(R_A), REG(R_D)},
    [0x83] = {ADD, REG(R_A), REG(R_E)},
    [0x84] = {ADD, REG(R_A), REG(R_H)},
    [0x85] = {ADD, REG(R_A), REG(R_L)},
    [0x86] = {ADD, REG(R_A), MEM_REG(R_HL)},
    [0x87] = {ADD, REG(R_A), REG(R_A)},
    [0x88] = {ADC, REG(R_A), REG(R_B)},
    [0x89] = {ADC, REG(R_A), REG(R_C)},
    [0x8A] = {ADC, REG(R_A), REG(R_D)},
    [0x8B] = {ADC, REG(R_A), REG(R_E)},
    [0x8C] = {ADC, REG(R_A), REG(R_H)},
    [0x8D] = {ADC, REG(R_A), REG(R_L)},
    [0x8E] = {ADC, REG(R_A), MEM_REG(R_HL)},
    [0x8F] = {ADC, REG(R_A), REG(R_A)},

    [0x90] = {SUB, REG(R_A), REG(R_B)},
    [0x91] = {SUB, REG(R_A), REG(R_C)},
    [0x92] = {SUB, REG(R_A), REG(R_D)},
    [0x93] = {SUB, REG(R_A), REG(R_E)},
    [0x94] = {SUB, REG(R_A), REG(R_H)},
    [0x95] = {SUB, REG(R_A), REG(R_L)},
    [0x96] = {SUB, REG(R_A), MEM_REG(R_HL)},
    [0x97] = {SUB, REG(R_A), REG(R_A)},
    [0x98] = {SBC, REG(R_A), REG(R_B)},
    [0x99] = {SBC, REG(R_A), REG(R_C)},
    [0x9A] = {SBC, REG(R_A), REG(R_D)},
    [0x9B] = {SBC, REG(R_A), REG(R_E)},
    [0x9C] = {SBC, REG(R_A), REG(R_H)},
    [0x9D] = {SBC, REG(R_A), REG(R_L)},
    [0x9E] = {SBC, REG(R_A), MEM_REG(R_HL)},
    [0x9F] = {SBC, REG(R_A), REG(R_A)},

    [0xA0] = {AND, REG(R_A), REG(R_B)},
    [0xA1] = {AND, REG(R_A), REG(R_C)},
    [0xA2] = {AND, REG(R_A), REG(R_D)},
    [0xA3] = {AND, REG(R_A), REG(R_E)},
    [0xA4] = {AND, REG(R_A), REG(R_H)},
    [0xA5] = {AND, REG(R_A), REG(R_L)},
    [0xA6] = {AND, REG(R_A), MEM_REG(R_HL)},
    [0xA7] = {AND, REG(R_A), REG(R_A)},
    [0xA8] = {XOR, REG(R_A), REG(R_B)},
    [0xA9] = {XOR, REG(R_A), REG(R_C)},
    [0xAA] = {XOR, REG(R_A), REG(R_D)},
    [0xAB] = {XOR, REG(R_A), REG(R_E)},
    [0xAC] = {XOR, REG(R_A), REG(R_H)},
    [0xAD] = {XOR, REG(R_A), REG(R_L)},
    [0xAE] = {XOR, REG(R_A), MEM_REG(R_HL)},
    [0xAF] = {XOR, REG(R_A), REG(R_A)},

    [0xB0] = {OR, REG(R_A), REG(R_B)},
    [0xB1] = {OR, REG(R_A), REG(R_C)},
    [0xB2] = {OR, REG(R_A), REG(R_D)},
    [0xB3] = {OR, REG(R_A), REG(R_E)},
    [0xB4] = {OR, REG(R_A), REG(R_H)},
    [0xB5] = {OR, REG(R_A), REG(R_L)},
    [0xB6] = {OR, REG(R_A), MEM_REG(R_HL)},
    [0xB7] = {OR, REG(R_A), REG(R_A)},
    [0xB8] = {CP, REG(R_A), REG(R_B)},
    [0xB9] = {CP, REG(R_A), REG(R_C)},
    [0xBA] = {CP, REG(R_A), REG(R_D)},
    [0xBB] = {CP, REG(R_A), REG(R_E)},
    [0xBC] = {CP, REG(R_A), REG(R_H)},
    [0xBD] = {CP, REG(R_A), REG(R_L)},
    [0xBE] = {CP, REG(R_A), MEM_REG(R_HL)},
    [0xBF] = {CP, REG(R_A), REG(R_A)},

    [0xC0] = {RET_NZ, NONE, NONE},
    [0xC1] = {POP, REG16(R_BC), NONE},
    [0xC2] = {JP_NZ, IMM16, NONE},
    [0xC3] = {JP, IMM16, NONE},
    [0xC4] = {CALL_NZ, IMM16, NONE},
    [0xC5] = {PUSH, REG16(R_BC), NONE},
    [0xC6] = {ADD, REG(R_A), IMM8},
    [0xC7] = {RST, IMM8, NONE},
    [0xC8] = {RET_Z, NONE, NONE},
    [0xC9] = {RET, NONE, NONE},
    [0xCA] = {JP_Z, IMM16, NONE},
    [0xCB] = {PREFIX, NONE, NONE},
    [0xCC] = {CALL_Z, IMM16, NONE},
    [0xCD] = {CALL, IMM16, NONE},
    [0xCE] = {ADC, REG(R_A), IMM8},
    [0xCF] = {RST, IMM8, NONE},

    [0xD0] = {RET_NC, NONE, NONE},
    [0xD1] = {POP, REG16(R_DE), NONE},
    [0xD2] = {JP_NC, IMM16, NONE},
    [0xD3] = {NOP, NONE, NONE},
    [0xD4] = {CALL_NC, IMM16, NONE},
    [0xD5] = {PUSH, REG16(R_DE), NONE},
    [0xD6] = {SUB, REG(R_A), IMM8},
    [0xD7] = {RST, IMM8, NONE},
    [0xD8] = {RET_C, NONE, NONE},
    [0xD9] = {RETI, NONE, NONE},
    [0xDA] = {JP_C, IMM16, NONE},
    [0xDB] = {NOP, NONE, NONE},
    [0xDC] = {CALL_C, IMM16, NONE},
    [0xDD] = {NOP, NONE, NONE},
    [0xDE] = {SBC, REG(R_A), IMM8},
    [0xDF] = {RST, IMM8, NONE},

    [0xE0] = {LDH, MEM_IMM8, REG(R_A)},
    [0xE1] = {POP, REG16(R_HL), NONE},
    [0xE2] = {LD, MEM_C, REG(R_A)},
    [0xE3] = {NOP, NONE, NONE},
    [0xE4] = {NOP, NONE, NONE},
    [0xE5] = {PUSH, REG16(R_HL), NONE},
    [0xE6] = {AND, REG(R_A), IMM8},
    [0xE7] = {RST, IMM8, NONE},
    [0xE8] = {ADD_SP, IMM8, NONE},
    [0xE9] = {JP_HL, NONE, NONE},
    [0xEA] = {LD, MEM_IMM16, REG(R_A)},
    [0xEB] = {NOP, NONE, NONE},
    [0xEC] = {NOP, NONE, NONE},
    [0xED] = {NOP, NONE, NONE},
    [0xEE] = {XOR, REG(R_A), IMM8},
    [0xEF] = {RST, IMM8, NONE},

    [0xF0] = {LDH, REG(R_A), MEM_IMM8},
    [0xF1] = {POP, REG16(R_AF), NONE},
    [0xF2] = {LD, REG(R_A), MEM_C},
    [0xF3] = {DI, NONE, NONE},
    [0xF4] = {NOP, NONE, NONE},
    [0xF5] = {PUSH, REG16(R_AF), NONE},
    [0xF6] = {OR, REG(R_A), IMM8},
    [0xF7] = {RST, IMM8, NONE},
    [0xF8] = {LD_HL_SP, IMM8, NONE},
    [0xF9] = {LD_SP_HL, NONE, NONE},
    [0xFA] = {LD, REG(R_A), MEM_IMM16},
    [0xFB] = {EI, NONE, NONE},
    [0xFC] = {NOP, NONE, NONE},
    [0xFD] = {NOP, NONE, NONE},
    [0xFE] = {CP, REG(R_A), IMM8},
    [0xFF] = {RST, IMM8, NONE},

};

instruction get_instruction(u8 byte) { return instruction_table[byte]; }
